// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLDGgkz9jWb5R7GWwOxJ9AA9IaY2qdNIQ',
    appId: '1:1070585457913:web:773ba1058625cc7cd70628',
    messagingSenderId: '1070585457913',
    projectId: 'fir-auth-fe965',
    authDomain: 'fir-auth-fe965.firebaseapp.com',
    storageBucket: 'fir-auth-fe965.firebasestorage.app',
    measurementId: 'G-83K2KH5FJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChzkuzr-UBSIGD5ENrkesIeUu7kkaLy3g',
    appId: '1:1070585457913:android:f00b98851cbb0ecfd70628',
    messagingSenderId: '1070585457913',
    projectId: 'fir-auth-fe965',
    storageBucket: 'fir-auth-fe965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ERpZvxuLB-Hwr0sHx05EbiBkVfyztgc',
    appId: '1:1070585457913:ios:2632cc632eb5b74dd70628',
    messagingSenderId: '1070585457913',
    projectId: 'fir-auth-fe965',
    storageBucket: 'fir-auth-fe965.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ERpZvxuLB-Hwr0sHx05EbiBkVfyztgc',
    appId: '1:1070585457913:ios:2632cc632eb5b74dd70628',
    messagingSenderId: '1070585457913',
    projectId: 'fir-auth-fe965',
    storageBucket: 'fir-auth-fe965.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLDGgkz9jWb5R7GWwOxJ9AA9IaY2qdNIQ',
    appId: '1:1070585457913:web:13b3bc10f895fbd8d70628',
    messagingSenderId: '1070585457913',
    projectId: 'fir-auth-fe965',
    authDomain: 'fir-auth-fe965.firebaseapp.com',
    storageBucket: 'fir-auth-fe965.firebasestorage.app',
    measurementId: 'G-8Y4NSHRM1T',
  );
}
